"""Initial migration

Revision ID: e5304037c3db
Revises: e78fc5fa636d
Create Date: 2024-11-03 15:53:10.248657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5304037c3db'
down_revision: Union[str, None] = 'e78fc5fa636d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_customer_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'customer', ['customer_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('cart_item_cart_id_fkey', 'cart_item', type_='foreignkey')
    op.drop_constraint('cart_item_product_id_fkey', 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'cart', ['cart_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'cart_item', 'product', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('order_customer_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'customer', ['customer_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('order_item_product_id_fkey', 'order_item', type_='foreignkey')
    op.drop_constraint('order_item_order_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('payment_order_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'order', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('product_category_product_id_fkey', 'product_category', type_='foreignkey')
    op.drop_constraint('product_category_category_id_fkey', 'product_category', type_='foreignkey')
    op.create_foreign_key(None, 'product_category', 'category', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'product_category', 'product', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product_category', schema='public', type_='foreignkey')
    op.create_foreign_key('product_category_category_id_fkey', 'product_category', 'category', ['category_id'], ['id'])
    op.create_foreign_key('product_category_product_id_fkey', 'product_category', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'payment', schema='public', type_='foreignkey')
    op.create_foreign_key('payment_order_id_fkey', 'payment', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_item', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_item', schema='public', type_='foreignkey')
    op.create_foreign_key('order_item_order_id_fkey', 'order_item', 'order', ['order_id'], ['id'])
    op.create_foreign_key('order_item_product_id_fkey', 'order_item', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'order', schema='public', type_='foreignkey')
    op.create_foreign_key('order_customer_id_fkey', 'order', 'customer', ['customer_id'], ['id'])
    op.drop_constraint(None, 'cart_item', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'cart_item', schema='public', type_='foreignkey')
    op.create_foreign_key('cart_item_product_id_fkey', 'cart_item', 'product', ['product_id'], ['id'])
    op.create_foreign_key('cart_item_cart_id_fkey', 'cart_item', 'cart', ['cart_id'], ['id'])
    op.drop_constraint(None, 'cart', schema='public', type_='foreignkey')
    op.create_foreign_key('cart_customer_id_fkey', 'cart', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
